#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_BranchBank

#include "Basic.hpp"

#include "A_BranchBank_classes.hpp"
#include "A_BranchBank_parameters.hpp"


namespace SDK
{

// Function A_BranchBank.A_BranchBank_C.ExecuteUbergraph_A_BranchBank
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_BranchBank_C::ExecuteUbergraph_A_BranchBank(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "ExecuteUbergraph_A_BranchBank");

	Params::A_BranchBank_C_ExecuteUbergraph_A_BranchBank Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_BranchBank.A_BranchBank_C.FirstResponders_Arrived
// (BlueprintCallable, BlueprintEvent)

void AA_BranchBank_C::FirstResponders_Arrived()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "FirstResponders_Arrived");

	UObject::ProcessEvent(Func, nullptr);
}


// Function A_BranchBank.A_BranchBank_C.Manager_Is_Scanned
// (BlueprintCallable, BlueprintEvent)

void AA_BranchBank_C::Manager_Is_Scanned()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "Manager_Is_Scanned");

	UObject::ProcessEvent(Func, nullptr);
}


// Function A_BranchBank.A_BranchBank_C.BndEvt__A_BranchBank_TriggerBox_ES_VO_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_BranchBank_C::BndEvt__A_BranchBank_TriggerBox_ES_VO_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "BndEvt__A_BranchBank_TriggerBox_ES_VO_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature");

	Params::A_BranchBank_C_BndEvt__A_BranchBank_TriggerBox_ES_VO_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_BranchBank.A_BranchBank_C.HeistStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// EPD3HeistState                          OldHeistState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPD3HeistState                          CurrentHeistState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_BranchBank_C::HeistStateChanged(EPD3HeistState OldHeistState, EPD3HeistState CurrentHeistState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "HeistStateChanged");

	Params::A_BranchBank_C_HeistStateChanged Parms{};

	Parms.OldHeistState = OldHeistState;
	Parms.CurrentHeistState = CurrentHeistState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_BranchBank.A_BranchBank_C.BndEvt__A_BranchBank_TriggerBox2_4_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_BranchBank_C::BndEvt__A_BranchBank_TriggerBox2_4_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "BndEvt__A_BranchBank_TriggerBox2_4_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature");

	Params::A_BranchBank_C_BndEvt__A_BranchBank_TriggerBox2_4_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_BranchBank.A_BranchBank_C.BndEvt__A_BranchBank_TriggerBox_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AActor*                           OverlappedActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AA_BranchBank_C::BndEvt__A_BranchBank_TriggerBox_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "BndEvt__A_BranchBank_TriggerBox_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature");

	Params::A_BranchBank_C_BndEvt__A_BranchBank_TriggerBox_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedActor = OverlappedActor;
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function A_BranchBank.A_BranchBank_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AA_BranchBank_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("A_BranchBank_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

