#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_BranchBank

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AkAudio_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass A_BranchBank.A_BranchBank_C
// 0x0098 (0x03D8 - 0x0340)
class AA_BranchBank_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Is_Manager_Near;                                   // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_349[0x7];                                      // 0x0349(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATriggerBox*                            TriggerBox_1_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAkAcousticPortal*                   SBZAkAcousticPortal93_4_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZSoundEnvironment*                   AMB_EXT_Front_Street_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_StreetSound_08_11_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_StreetSound_03_12_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_Eye_scanner_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZDestroyGroup*                       SBZDestroyGroup_VO_Trigger_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0380(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_PoliceMegaphone_15_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_HouseSparrow_4_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0390(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_HouseSparrow_3_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x0398(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_HouseSparrow_2_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_HouseSparrow_01_14_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_Dog_3_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_Pigeons_2_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_Pigeons_01_2_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_DistantSiren_2_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZAmbientSound*                       SBZAmbientSound_DistantSiren_01_16_ExecuteUbergraph_A_BranchBank_RefProperty; // 0x03D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_A_BranchBank(int32 EntryPoint);
	void FirstResponders_Arrived();
	void Manager_Is_Scanned();
	void BndEvt__A_BranchBank_TriggerBox_ES_VO_K2Node_ActorBoundEvent_2_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void HeistStateChanged(EPD3HeistState OldHeistState, EPD3HeistState CurrentHeistState);
	void BndEvt__A_BranchBank_TriggerBox2_4_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__A_BranchBank_TriggerBox_1_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("A_BranchBank_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"A_BranchBank_C")
	}
	static class AA_BranchBank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AA_BranchBank_C>();
	}
};
DUMPER7_ASSERTS_AA_BranchBank_C;

}

