#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Placeable_SentryGun

#include "Basic.hpp"

#include "ABP_Placeable_SentryGun_classes.hpp"
#include "ABP_Placeable_SentryGun_parameters.hpp"


namespace SDK
{

// Function ABP_Placeable_SentryGun.ABP_Placeable_SentryGun_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Placeable_SentryGun_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Placeable_SentryGun_C", "AnimGraph");

	Params::ABP_Placeable_SentryGun_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_Placeable_SentryGun.ABP_Placeable_SentryGun_C.ExecuteUbergraph_ABP_Placeable_SentryGun
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Placeable_SentryGun_C::ExecuteUbergraph_ABP_Placeable_SentryGun(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Placeable_SentryGun_C", "ExecuteUbergraph_ABP_Placeable_SentryGun");

	Params::ABP_Placeable_SentryGun_C_ExecuteUbergraph_ABP_Placeable_SentryGun Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

