#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Charm_Base_Flat

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ABP_Charm_Base_Flat.ABP_Charm_Base_Flat_C.ExecuteUbergraph_ABP_Charm_Base_Flat
// 0x0004 (0x0004 - 0x0000)
struct ABP_Charm_Base_Flat_C_ExecuteUbergraph_ABP_Charm_Base_Flat final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_Charm_Base_Flat_C_ExecuteUbergraph_ABP_Charm_Base_Flat;

// Function ABP_Charm_Base_Flat.ABP_Charm_Base_Flat_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_Charm_Base_Flat_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ABP_Charm_Base_Flat_C_AnimGraph;

}

