#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Collectors_Edition

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Collectors_Edition.BP_Collectors_Edition_C.UserConstructionScript
// 0x0008 (0x0008 - 0x0000)
struct BP_Collectors_Edition_C_UserConstructionScript final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Collectors_Edition_C_UserConstructionScript;

}

