#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Collectors_Edition

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Collectors_Edition.BP_Collectors_Edition_C
// 0x0008 (0x0350 - 0x0348)
class ABP_Collectors_Edition_C final : public ASBZMask
{
public:
	class UMaterialInstanceDynamic*               DynMat;                                            // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Collectors_Edition_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Collectors_Edition_C")
	}
	static class ABP_Collectors_Edition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Collectors_Edition_C>();
	}
};
DUMPER7_ASSERTS_ABP_Collectors_Edition_C;

}

