#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClassifiedPapers

#include "Basic.hpp"

#include "BP_ClassifiedPapers_classes.hpp"
#include "BP_ClassifiedPapers_parameters.hpp"


namespace SDK
{

// Function BP_ClassifiedPapers.BP_ClassifiedPapers_C.ExecuteUbergraph_BP_ClassifiedPapers
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ClassifiedPapers_C::ExecuteUbergraph_BP_ClassifiedPapers(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassifiedPapers_C", "ExecuteUbergraph_BP_ClassifiedPapers");

	Params::BP_ClassifiedPapers_C_ExecuteUbergraph_BP_ClassifiedPapers Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ClassifiedPapers.BP_ClassifiedPapers_C.BndEvt__BP_PortableSSD_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ClassifiedPapers_C::BndEvt__BP_PortableSSD_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClassifiedPapers_C", "BndEvt__BP_PortableSSD_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature");

	Params::BP_ClassifiedPapers_C_BndEvt__BP_PortableSSD_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable_0 = Interactable_0;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}

}

