#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Collectors_Edition

#include "Basic.hpp"

#include "BP_Collectors_Edition_classes.hpp"
#include "BP_Collectors_Edition_parameters.hpp"


namespace SDK
{

// Function BP_Collectors_Edition.BP_Collectors_Edition_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Collectors_Edition_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Collectors_Edition_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

