#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Charm_Common

#include "Basic.hpp"

#include "BP_Charm_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Charm_Common.BP_Charm_Common_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_Charm_Common_C final : public ABP_Charm_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Charm_Common_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Charm_Common_C")
	}
	static class ABP_Charm_Common_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Charm_Common_C>();
	}
};
DUMPER7_ASSERTS_ABP_Charm_Common_C;

}

