#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ElevatorDoor_ControlPanel

#include "Basic.hpp"

#include "BP_ElevatorDoor_ControlPanel_classes.hpp"
#include "BP_ElevatorDoor_ControlPanel_parameters.hpp"


namespace SDK
{

// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.ExecuteUbergraph_BP_ElevatorDoor_ControlPanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ElevatorDoor_ControlPanel_C::ExecuteUbergraph_BP_ElevatorDoor_ControlPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "ExecuteUbergraph_BP_ElevatorDoor_ControlPanel");

	Params::BP_ElevatorDoor_ControlPanel_C_ExecuteUbergraph_BP_ElevatorDoor_ControlPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.BndEvt__BP_ElevatorDoor_ControlPanel_WaypointSBZBinaryState_K2Node_ComponentBoundEvent_2_SBZBinaryStateChangedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bState_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ElevatorDoor_ControlPanel_C::BndEvt__BP_ElevatorDoor_ControlPanel_WaypointSBZBinaryState_K2Node_ComponentBoundEvent_2_SBZBinaryStateChangedSignature__DelegateSignature(bool bState_0, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "BndEvt__BP_ElevatorDoor_ControlPanel_WaypointSBZBinaryState_K2Node_ComponentBoundEvent_2_SBZBinaryStateChangedSignature__DelegateSignature");

	Params::BP_ElevatorDoor_ControlPanel_C_BndEvt__BP_ElevatorDoor_ControlPanel_WaypointSBZBinaryState_K2Node_ComponentBoundEvent_2_SBZBinaryStateChangedSignature__DelegateSignature Parms{};

	Parms.bState_0 = bState_0;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ElevatorDoor_ControlPanel_C::BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature");

	Params::BP_ElevatorDoor_ControlPanel_C_BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable_0 = Interactable_0;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ElevatorDoor_ControlPanel_C::BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature");

	Params::BP_ElevatorDoor_ControlPanel_C_BndEvt__BP_ElevatorDoor_ControlPanel_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable_0 = Interactable_0;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ElevatorDoor_ControlPanel_C::OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "OnStateChanged");

	Params::BP_ElevatorDoor_ControlPanel_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo = bStateToChangeTo;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ElevatorDoor_ControlPanel_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.SetInteractionEnable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Interaction_Enabled                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    waypointEnabled                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ElevatorDoor_ControlPanel_C::SetInteractionEnable(bool Interaction_Enabled, bool waypointEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "SetInteractionEnable");

	Params::BP_ElevatorDoor_ControlPanel_C_SetInteractionEnable Parms{};

	Parms.Interaction_Enabled = Interaction_Enabled;
	Parms.waypointEnabled = waypointEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.PlayTurnOff
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ElevatorDoor_ControlPanel_C::PlayTurnOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "PlayTurnOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.PlayTurnOn
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ElevatorDoor_ControlPanel_C::PlayTurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "PlayTurnOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ElevatorDoor_ControlPanel.BP_ElevatorDoor_ControlPanel_C.SetMarker
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class USBZMarkerDataAsset*        MarkerDataAsset                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ElevatorDoor_ControlPanel_C::SetMarker(const class USBZMarkerDataAsset* MarkerDataAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ElevatorDoor_ControlPanel_C", "SetMarker");

	Params::BP_ElevatorDoor_ControlPanel_C_SetMarker Parms{};

	Parms.MarkerDataAsset = MarkerDataAsset;

	UObject::ProcessEvent(Func, &Parms);
}

}

