#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FacadeWindow_01_A_NAV_BLI

#include "Basic.hpp"

#include "BP_IGL_BRE_NAV_ATT_2HITS_BLI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FacadeWindow_01_A_NAV_BLI.BP_FacadeWindow_01_A_NAV_BLI_C
// 0x0000 (0x0608 - 0x0608)
class ABP_FacadeWindow_01_A_NAV_BLI_C final : public ABP_IGL_BRE_NAV_ATT_2HITS_BLI_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FacadeWindow_01_A_NAV_BLI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FacadeWindow_01_A_NAV_BLI_C")
	}
	static class ABP_FacadeWindow_01_A_NAV_BLI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FacadeWindow_01_A_NAV_BLI_C>();
	}
};
DUMPER7_ASSERTS_ABP_FacadeWindow_01_A_NAV_BLI_C;

}

