#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Int_SingleDoor_Reinforced_FireExit_01

#include "Basic.hpp"

#include "BP_InteractableUnBreachableSingleDoor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Int_SingleDoor_Reinforced_FireExit_01.BP_Int_SingleDoor_Reinforced_FireExit_01_C
// 0x0008 (0x0678 - 0x0670)
class ABP_Int_SingleDoor_Reinforced_FireExit_01_C final : public ABP_InteractableUnBreachableSingleDoor_C
{
public:
	class UStaticMeshComponent*                   PushBar_01_A;                                      // 0x0670(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Int_SingleDoor_Reinforced_FireExit_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Int_SingleDoor_Reinforced_FireExit_01_C")
	}
	static class ABP_Int_SingleDoor_Reinforced_FireExit_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Int_SingleDoor_Reinforced_FireExit_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_Int_SingleDoor_Reinforced_FireExit_01_C;

}

