#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IGL_BRE_NAV_ATT_2HITS_BLI

#include "Basic.hpp"

#include "BPS_GlassHit_VFXData_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IGL_BRE_NAV_ATT_2HITS_BLI.BP_IGL_BRE_NAV_ATT_2HITS_BLI_C
// 0x0080 (0x0608 - 0x0588)
class ABP_IGL_BRE_NAV_ATT_2HITS_BLI_C : public ASBZWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0588(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USBZRoomConnectorComponent*             SBZRoomConnector;                                  // 0x0590(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZPropDamageComponent*                SBZPropDamage;                                     // 0x0598(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Window;                                            // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_ReplicatedBinaryActor_windows_blinder_C* Blinder;                                      // 0x05A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Particle_count;                                    // 0x05B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Particles_Color;                                   // 0x05B4(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Particle_Size_Multiplier;                          // 0x05C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Do_Cosmetics;                                      // 0x05C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5C9[0x7];                                      // 0x05C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             DamageInstigator;                                  // 0x05D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FBPS_GlassHit_VFXData>          VFX;                                               // 0x05D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TMulticastInlineDelegate<void()>              onGlassDamaged;                                    // 0x05E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              onGlassDestroyed;                                  // 0x05F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_BP_IGL_BRE_NAV_ATT_2HITS_BLI(int32 EntryPoint);
	void OnStateChanged(ESBZGateState OldState, ESBZGateState NewState, bool bIsInitialStateChange);
	void BndEvt__BP_BreachableWindow_SBZPropDamage_K2Node_ComponentBoundEvent_0_SBZPropDamageHitsSignature__DelegateSignature(class UActorComponent* PoolComponent, int32 Hits, bool bDoCosmetics, const struct FSBZPropDamageContext& DamageContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IGL_BRE_NAV_ATT_2HITS_BLI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IGL_BRE_NAV_ATT_2HITS_BLI_C")
	}
	static class ABP_IGL_BRE_NAV_ATT_2HITS_BLI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_IGL_BRE_NAV_ATT_2HITS_BLI_C>();
	}
};
DUMPER7_ASSERTS_ABP_IGL_BRE_NAV_ATT_2HITS_BLI_C;

}

