#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Keypad

#include "Basic.hpp"

#include "BP_Keypad_classes.hpp"
#include "BP_Keypad_parameters.hpp"


namespace SDK
{

// Function BP_Keypad.BP_Keypad_C.ExecuteUbergraph_BP_Keypad
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Keypad_C::ExecuteUbergraph_BP_Keypad(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "ExecuteUbergraph_BP_Keypad");

	Params::BP_Keypad_C_ExecuteUbergraph_BP_Keypad Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_OnKeypadFocusChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             KeyIndex                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInNewState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Keypad_C::BP_OnKeypadFocusChanged(const int32 KeyIndex, bool bInNewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_OnKeypadFocusChanged");

	Params::BP_Keypad_C_BP_OnKeypadFocusChanged Parms{};

	Parms.KeyIndex = KeyIndex;
	Parms.bInNewState = bInNewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_UpdateHighlights
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<int32>&                    GeneratedCode                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Keypad_C::BP_UpdateHighlights(const TArray<int32>& GeneratedCode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_UpdateHighlights");

	Params::BP_Keypad_C_BP_UpdateHighlights Parms{};

	Parms.GeneratedCode = std::move(GeneratedCode);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ESBZModuleActorState                    NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Keypad_C::BP_OnStateChanged(ESBZModuleActorState NewState, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_OnStateChanged");

	Params::BP_Keypad_C_BP_OnStateChanged Parms{};

	Parms.NewState = NewState;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_OnGuessedCodeChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      GuessedCodeText                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Keypad_C::BP_OnGuessedCodeChanged(const class FText& GuessedCodeText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_OnGuessedCodeChanged");

	Params::BP_Keypad_C_BP_OnGuessedCodeChanged Parms{};

	Parms.GuessedCodeText = std::move(GuessedCodeText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_HandleLanternOverlapEnd
// (BlueprintCosmetic, Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class AActor*>&            PlayerAttachedActors                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Keypad_C::BP_HandleLanternOverlapEnd(const TArray<class AActor*>& PlayerAttachedActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_HandleLanternOverlapEnd");

	Params::BP_Keypad_C_BP_HandleLanternOverlapEnd Parms{};

	Parms.PlayerAttachedActors = std::move(PlayerAttachedActors);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_HandleLanternOverlapBegin
// (BlueprintCosmetic, Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class AActor*>&            PlayerAttachedActors                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class USkeletalMeshComponent*           PlayerMesh                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             SocketToAttach                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FTransform&                SpawnTransform                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)

void ABP_Keypad_C::BP_HandleLanternOverlapBegin(const TArray<class AActor*>& PlayerAttachedActors, class USkeletalMeshComponent* PlayerMesh, class FName SocketToAttach, const struct FTransform& SpawnTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_HandleLanternOverlapBegin");

	Params::BP_Keypad_C_BP_HandleLanternOverlapBegin Parms{};

	Parms.PlayerAttachedActors = std::move(PlayerAttachedActors);
	Parms.PlayerMesh = PlayerMesh;
	Parms.SocketToAttach = SocketToAttach;
	Parms.SpawnTransform = std::move(SpawnTransform);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.BP_OnKeypadPressed
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             KeyIndexPressed                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Keypad_C::BP_OnKeypadPressed(const int32 KeyIndexPressed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "BP_OnKeypadPressed");

	Params::BP_Keypad_C_BP_OnKeypadPressed Parms{};

	Parms.KeyIndexPressed = KeyIndexPressed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.CurveEvalTick_1117234D45361F2B8DD22A9E49175EB4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UCurveFloatDelegateTimer*   CurveFloatTimer                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveElapsedTime                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveTimeSinceLast                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Keypad_C::CurveEvalTick_1117234D45361F2B8DD22A9E49175EB4(const class UCurveFloatDelegateTimer* CurveFloatTimer, float CurveElapsedTime, float CurveTimeSinceLast, float CurveValue, float CurveTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "CurveEvalTick_1117234D45361F2B8DD22A9E49175EB4");

	Params::BP_Keypad_C_CurveEvalTick_1117234D45361F2B8DD22A9E49175EB4 Parms{};

	Parms.CurveFloatTimer = CurveFloatTimer;
	Parms.CurveElapsedTime = CurveElapsedTime;
	Parms.CurveTimeSinceLast = CurveTimeSinceLast;
	Parms.CurveValue = CurveValue;
	Parms.CurveTime = CurveTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.CurveFinished_1117234D45361F2B8DD22A9E49175EB4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UCurveFloatDelegateTimer*   CurveFloatTimer                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveElapsedTime                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveTimeSinceLast                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CurveTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Keypad_C::CurveFinished_1117234D45361F2B8DD22A9E49175EB4(const class UCurveFloatDelegateTimer* CurveFloatTimer, float CurveElapsedTime, float CurveTimeSinceLast, float CurveValue, float CurveTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "CurveFinished_1117234D45361F2B8DD22A9E49175EB4");

	Params::BP_Keypad_C_CurveFinished_1117234D45361F2B8DD22A9E49175EB4 Parms{};

	Parms.CurveFloatTimer = CurveFloatTimer;
	Parms.CurveElapsedTime = CurveElapsedTime;
	Parms.CurveTimeSinceLast = CurveTimeSinceLast;
	Parms.CurveValue = CurveValue;
	Parms.CurveTime = CurveTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Keypad.BP_Keypad_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Keypad_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Keypad_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

