#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyWindow_01_NAV

#include "Basic.hpp"

#include "BP_IGL_BRE_NAV_ATT_2HITS_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LobbyWindow_01_NAV.BP_LobbyWindow_01_NAV_C
// 0x0000 (0x05F8 - 0x05F8)
class ABP_LobbyWindow_01_NAV_C final : public ABP_IGL_BRE_NAV_ATT_2HITS_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LobbyWindow_01_NAV_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LobbyWindow_01_NAV_C")
	}
	static class ABP_LobbyWindow_01_NAV_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LobbyWindow_01_NAV_C>();
	}
};
DUMPER7_ASSERTS_ABP_LobbyWindow_01_NAV_C;

}

