#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RangedWeapon_AssaultRifle_VF7S

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RangedWeapon_AssaultRifle_VF7S.BP_RangedWeapon_AssaultRifle_VF7S_C
// 0x0000 (0x0750 - 0x0750)
class ABP_RangedWeapon_AssaultRifle_VF7S_C final : public ASBZRangedWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RangedWeapon_AssaultRifle_VF7S_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RangedWeapon_AssaultRifle_VF7S_C")
	}
	static class ABP_RangedWeapon_AssaultRifle_VF7S_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RangedWeapon_AssaultRifle_VF7S_C>();
	}
};
DUMPER7_ASSERTS_ABP_RangedWeapon_AssaultRifle_VF7S_C;

}

