#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReplicatedBinaryActor_bollard

#include "Basic.hpp"

#include "BP_ReplicatedBinaryActor_bollard_classes.hpp"
#include "BP_ReplicatedBinaryActor_bollard_parameters.hpp"


namespace SDK
{

// Function BP_ReplicatedBinaryActor_bollard.BP_ReplicatedBinaryActor_bollard_C.ExecuteUbergraph_BP_ReplicatedBinaryActor_bollard
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ReplicatedBinaryActor_bollard_C::ExecuteUbergraph_BP_ReplicatedBinaryActor_bollard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_bollard_C", "ExecuteUbergraph_BP_ReplicatedBinaryActor_bollard");

	Params::BP_ReplicatedBinaryActor_bollard_C_ExecuteUbergraph_BP_ReplicatedBinaryActor_bollard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ReplicatedBinaryActor_bollard.BP_ReplicatedBinaryActor_bollard_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ReplicatedBinaryActor_bollard_C::OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_bollard_C", "OnStateChanged");

	Params::BP_ReplicatedBinaryActor_bollard_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo = bStateToChangeTo;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ReplicatedBinaryActor_bollard.BP_ReplicatedBinaryActor_bollard_C.MoveBollard__UpdateFunc
// (BlueprintEvent)

void ABP_ReplicatedBinaryActor_bollard_C::MoveBollard__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_bollard_C", "MoveBollard__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ReplicatedBinaryActor_bollard.BP_ReplicatedBinaryActor_bollard_C.MoveBollard__FinishedFunc
// (BlueprintEvent)

void ABP_ReplicatedBinaryActor_bollard_C::MoveBollard__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_bollard_C", "MoveBollard__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

