#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RangedWeapon_OVK_HET5

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RangedWeapon_OVK_HET5.BP_RangedWeapon_OVK_HET5_C
// 0x0000 (0x0790 - 0x0790)
class ABP_RangedWeapon_OVK_HET5_C final : public ASBZThermalScopeWeapon
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RangedWeapon_OVK_HET5_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RangedWeapon_OVK_HET5_C")
	}
	static class ABP_RangedWeapon_OVK_HET5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RangedWeapon_OVK_HET5_C>();
	}
};
DUMPER7_ASSERTS_ABP_RangedWeapon_OVK_HET5_C;

}

