#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SecurityGate_02

#include "Basic.hpp"

#include "BP_InteractableUnBreachableSingleDoor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SecurityGate_02.BP_SecurityGate_02_C
// 0x0008 (0x0678 - 0x0670)
class ABP_SecurityGate_02_C final : public ABP_InteractableUnBreachableSingleDoor_C
{
public:
	class UStaticMeshComponent*                   SecurityGate_02_Glass;                             // 0x0670(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SecurityGate_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SecurityGate_02_C")
	}
	static class ABP_SecurityGate_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SecurityGate_02_C>();
	}
};
DUMPER7_ASSERTS_ABP_SecurityGate_02_C;

}

