#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BranchBank

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BranchBank.BranchBank_C
// 0x0000 (0x0340 - 0x0340)
class ABranchBank_C final : public ASBZLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BranchBank_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BranchBank_C")
	}
	static class ABranchBank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABranchBank_C>();
	}
};
DUMPER7_ASSERTS_ABranchBank_C;

}

