#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_BranchBank_IntroOutroSequence

#include "Basic.hpp"

#include "C_BranchBank_IntroOutroSequence_classes.hpp"
#include "C_BranchBank_IntroOutroSequence_parameters.hpp"


namespace SDK
{

// Function C_BranchBank_IntroOutroSequence.C_BranchBank_IntroOutroSequence_C.ExecuteUbergraph_C_BranchBank_IntroOutroSequence
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AC_BranchBank_IntroOutroSequence_C::ExecuteUbergraph_C_BranchBank_IntroOutroSequence(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_BranchBank_IntroOutroSequence_C", "ExecuteUbergraph_C_BranchBank_IntroOutroSequence");

	Params::C_BranchBank_IntroOutroSequence_C_ExecuteUbergraph_C_BranchBank_IntroOutroSequence Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function C_BranchBank_IntroOutroSequence.C_BranchBank_IntroOutroSequence_C.IntroSequenceChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsStarted                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AC_BranchBank_IntroOutroSequence_C::IntroSequenceChanged(bool bIsStarted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_BranchBank_IntroOutroSequence_C", "IntroSequenceChanged");

	Params::C_BranchBank_IntroOutroSequence_C_IntroSequenceChanged Parms{};

	Parms.bIsStarted = bIsStarted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function C_BranchBank_IntroOutroSequence.C_BranchBank_IntroOutroSequence_C.OnIntroFinished
// (BlueprintCallable, BlueprintEvent)

void AC_BranchBank_IntroOutroSequence_C::OnIntroFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_BranchBank_IntroOutroSequence_C", "OnIntroFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

