#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_BranchBank_IntroOutroSequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass C_BranchBank_IntroOutroSequence.C_BranchBank_IntroOutroSequence_C
// 0x0010 (0x0350 - 0x0340)
class AC_BranchBank_IntroOutroSequence_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ALevelSequenceActor*                    C_NoRestForTheWiked_Master_01_ExecuteUbergraph_C_BranchBank_IntroOutroSequence_RefProperty; // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_C_BranchBank_IntroOutroSequence(int32 EntryPoint);
	void IntroSequenceChanged(bool bIsStarted);
	void OnIntroFinished();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_BranchBank_IntroOutroSequence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_BranchBank_IntroOutroSequence_C")
	}
	static class AC_BranchBank_IntroOutroSequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AC_BranchBank_IntroOutroSequence_C>();
	}
};
DUMPER7_ASSERTS_AC_BranchBank_IntroOutroSequence_C;

}

