#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_Collision

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass G_BranchBank_Collision.G_BranchBank_Collision_C
// 0x0000 (0x0340 - 0x0340)
class AG_BranchBank_Collision_C final : public ASBZLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("G_BranchBank_Collision_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"G_BranchBank_Collision_C")
	}
	static class AG_BranchBank_Collision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AG_BranchBank_Collision_C>();
	}
};
DUMPER7_ASSERTS_AG_BranchBank_Collision_C;

}

