#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_Coverpoints

#include "Basic.hpp"

#include "G_BranchBank_Coverpoints_classes.hpp"
#include "G_BranchBank_Coverpoints_parameters.hpp"


namespace SDK
{

// Function G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C.ExecuteUbergraph_G_BranchBank_Coverpoints
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AG_BranchBank_Coverpoints_C::ExecuteUbergraph_G_BranchBank_Coverpoints(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_Coverpoints_C", "ExecuteUbergraph_G_BranchBank_Coverpoints");

	Params::G_BranchBank_Coverpoints_C_ExecuteUbergraph_G_BranchBank_Coverpoints Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C.BranchBank_Roof
// (BlueprintCallable, BlueprintEvent)

void AG_BranchBank_Coverpoints_C::BranchBank_Roof()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_Coverpoints_C", "BranchBank_Roof");

	UObject::ProcessEvent(Func, nullptr);
}


// Function G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C.BranchBank_Stairs
// (BlueprintCallable, BlueprintEvent)

void AG_BranchBank_Coverpoints_C::BranchBank_Stairs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_Coverpoints_C", "BranchBank_Stairs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C.BranchBank_Kitchen
// (BlueprintCallable, BlueprintEvent)

void AG_BranchBank_Coverpoints_C::BranchBank_Kitchen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_Coverpoints_C", "BranchBank_Kitchen");

	UObject::ProcessEvent(Func, nullptr);
}

}

