#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_LivingWorld

#include "Basic.hpp"

#include "G_BranchBank_LivingWorld_classes.hpp"
#include "G_BranchBank_LivingWorld_parameters.hpp"


namespace SDK
{

// Function G_BranchBank_LivingWorld.G_BranchBank_LivingWorld_C.ExecuteUbergraph_G_BranchBank_LivingWorld
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AG_BranchBank_LivingWorld_C::ExecuteUbergraph_G_BranchBank_LivingWorld(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_LivingWorld_C", "ExecuteUbergraph_G_BranchBank_LivingWorld");

	Params::G_BranchBank_LivingWorld_C_ExecuteUbergraph_G_BranchBank_LivingWorld Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function G_BranchBank_LivingWorld.G_BranchBank_LivingWorld_C.BlackScreenStarted
// (Event, Public, BlueprintEvent)

void AG_BranchBank_LivingWorld_C::BlackScreenStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("G_BranchBank_LivingWorld_C", "BlackScreenStarted");

	UObject::ProcessEvent(Func, nullptr);
}

}

