#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_Navlinks

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"


namespace SDK::Params
{

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.ExecuteUbergraph_G_BranchBank_Navlinks
// 0x0130 (0x0130 - 0x0000)
struct G_BranchBank_Navlinks_C_ExecuteUbergraph_G_BranchBank_Navlinks final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_B3C3F99640B3A17D5F1F45BF7DCCE688_Variable; // 0x0004(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_B8179CAF40D2C0F986B3BCB288B9E0FE_Variable; // 0x0008(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_65332CF44AC4D1FBBB7D51BD8D06338A_Variable; // 0x0018(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initialized_73655FE8410E436CAC3B2482BCE20F95_Variable; // 0x0019(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initialized_96F0163A40A325EBFFA4F7BA8F5F981B_Variable; // 0x001A(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B[0x1];                                       // 0x001B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Current_Value_73655FE8410E436CAC3B2482BCE20F95_Variable; // 0x001C(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_362552FB4F1331729735A6ABE8B8C26C_Variable; // 0x0020(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_2;          // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_3;          // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_96F0163A40A325EBFFA4F7BA8F5F981B_Variable; // 0x0030(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_6;             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_6;               // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_4;          // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_5;             // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_5;               // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_4;             // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_4;               // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_3;             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_3;               // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_2;             // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_2;               // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_1;             // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_1;               // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable;               // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor;                 // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                K2Node_Event_OldHeistState;                        // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                K2Node_Event_CurrentHeistState;                    // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ActorBoundEvent_DestroyedActor;             // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DamagedActor;               // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ActorBoundEvent_Damage;                     // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      K2Node_ActorBoundEvent_DamageType;                 // 0x00D0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_ActorBoundEvent_InstigatedBy;               // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DamageCauser;               // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_B8179CAF40D2C0F986B3BCB288B9E0FE_Variable; // 0x00E8(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initialized_13E838E64504C35AEBED3C82F3BB8D32_Variable; // 0x00E9(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initialized_362552FB4F1331729735A6ABE8B8C26C_Variable; // 0x00EA(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_EB[0x1];                                       // 0x00EB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Current_Value_13E838E64504C35AEBED3C82F3BB8D32_Variable; // 0x00EC(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_5;          // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_16;                // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_16;                   // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_15;                // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_15;                   // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_14;                // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_14;                   // 0x00FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FE[0x2];                                       // 0x00FE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Current_Value_65332CF44AC4D1FBBB7D51BD8D06338A_Variable; // 0x0100(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_6;          // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_B3C3F99640B3A17D5F1F45BF7DCCE688_Variable; // 0x010C(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_13;                // 0x010D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_13;                   // 0x010E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_12;                // 0x010F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_12;                   // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_11;                // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_11;                   // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_10;                // 0x0113(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_10;                   // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_9;                 // 0x0115(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_9;                    // 0x0116(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_8;                 // 0x0117(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_8;                    // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_7;                 // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_7;                    // 0x011A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_6;                 // 0x011B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_6;                    // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_5;                 // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_5;                    // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_4;                 // 0x011F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_4;                    // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_3;                 // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_3;                    // 0x0122(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_2;                 // 0x0123(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_2;                    // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_1;                 // 0x0125(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_1;                    // 0x0126(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState;                   // 0x0127(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State;                      // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_ExecuteUbergraph_G_BranchBank_Navlinks;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature
// 0x0028 (0x0028 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature final
{
public:
	class AActor*                                 DamagedActor;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      DamageType;                                        // 0x0010(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            InstigatedBy;                                      // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.HeistStateChanged
// 0x0002 (0x0002 - 0x0000)
struct G_BranchBank_Navlinks_C_HeistStateChanged final
{
public:
	EPD3HeistState                                OldHeistState;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                CurrentHeistState;                                 // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_HeistStateChanged;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature;

// Function G_BranchBank_Navlinks.G_BranchBank_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature;

}

