#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_Coverpoints

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C
// 0x0020 (0x0360 - 0x0340)
class AG_BranchBank_Coverpoints_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASBZRoomVolume*                         SBZRoomVolume_ServerRoom2_ExecuteUbergraph_G_BranchBank_Coverpoints_RefProperty; // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZRoomVolume*                         SBZRoomVolume_ServerRoom_ExecuteUbergraph_G_BranchBank_Coverpoints_RefProperty; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZRoomVolume*                         SBZRoomVolume_MaintainanceRoom_ExecuteUbergraph_G_BranchBank_Coverpoints_RefProperty; // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_G_BranchBank_Coverpoints(int32 EntryPoint);
	void BranchBank_Roof();
	void BranchBank_Stairs();
	void BranchBank_Kitchen();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("G_BranchBank_Coverpoints_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"G_BranchBank_Coverpoints_C")
	}
	static class AG_BranchBank_Coverpoints_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AG_BranchBank_Coverpoints_C>();
	}
};
DUMPER7_ASSERTS_AG_BranchBank_Coverpoints_C;

}

