#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_LivingWorld

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"


namespace SDK::Params
{

// Function G_BranchBank_LivingWorld.G_BranchBank_LivingWorld_C.ExecuteUbergraph_G_BranchBank_LivingWorld
// 0x0420 (0x0420 - 0x0000)
struct G_BranchBank_LivingWorld_C_ExecuteUbergraph_G_BranchBank_LivingWorld final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue;              // 0x0008(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_1;            // 0x0018(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_2;            // 0x0028(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_3;            // 0x0038(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_4;            // 0x0048(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_5;            // 0x0058(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_6;            // 0x0068(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_7;            // 0x0078(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_8;            // 0x0088(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_9;            // 0x0098(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_10;           // 0x00A8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_11;           // 0x00B8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_12;           // 0x00C8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_13;           // 0x00D8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_14;           // 0x00E8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_15;           // 0x00F8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_16;           // 0x0108(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_17;           // 0x0118(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_18;           // 0x0128(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_19;           // 0x0138(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_20;           // 0x0148(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_21;           // 0x0158(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_22;           // 0x0168(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue; // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_1; // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_2; // 0x017A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_17B[0x5];                                      // 0x017B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_23;           // 0x0180(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_3; // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_4; // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_5; // 0x0192(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_193[0x5];                                      // 0x0193(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_24;           // 0x0198(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_6; // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_25;           // 0x01B0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_26;           // 0x01C0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_27;           // 0x01D0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_28;           // 0x01E0(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_7; // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_8; // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F2[0x6];                                      // 0x01F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_29;           // 0x01F8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_30;           // 0x0208(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_31;           // 0x0218(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_32;           // 0x0228(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_33;           // 0x0238(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_34;           // 0x0248(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_9; // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_10; // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_11; // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25B[0x5];                                      // 0x025B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_35;           // 0x0260(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_12; // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_36;           // 0x0278(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_37;           // 0x0288(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_38;           // 0x0298(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_39;           // 0x02A8(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_40;           // 0x02B8(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_13; // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_41;           // 0x02D0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_42;           // 0x02E0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_43;           // 0x02F0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_44;           // 0x0300(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_45;           // 0x0310(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_46;           // 0x0320(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_47;           // 0x0330(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_48;           // 0x0340(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_49;           // 0x0350(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_14; // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x7];                                      // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_50;           // 0x0368(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_15; // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_51;           // 0x0380(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_52;           // 0x0390(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_53;           // 0x03A0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_54;           // 0x03B0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_55;           // 0x03C0(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_16; // 0x03D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D1[0x7];                                      // 0x03D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_56;           // 0x03D8(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_GetRandomBoolWithWeightFromStreamMixed_ReturnValue_17; // 0x03E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E9[0x7];                                      // 0x03E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_57;           // 0x03F0(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_58;           // 0x0400(0x0010)(HasGetValueTypeHash)
	struct FSBZPawnSpawnRequestHandle             CallFunc_SpawnPredefined_ReturnValue_59;           // 0x0410(0x0010)(HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_LivingWorld_C_ExecuteUbergraph_G_BranchBank_LivingWorld;

}

