#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_BranchBank_Coverpoints

#include "Basic.hpp"


namespace SDK::Params
{

// Function G_BranchBank_Coverpoints.G_BranchBank_Coverpoints_C.ExecuteUbergraph_G_BranchBank_Coverpoints
// 0x0004 (0x0004 - 0x0000)
struct G_BranchBank_Coverpoints_C_ExecuteUbergraph_G_BranchBank_Coverpoints final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_BranchBank_Coverpoints_C_ExecuteUbergraph_G_BranchBank_Coverpoints;

}

