#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_HET5_AOE

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HET5_AOE.GE_HET5_AOE_C
// 0x0000 (0x08C0 - 0x08C0)
class UGE_HET5_AOE_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_HET5_AOE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_HET5_AOE_C")
	}
	static class UGE_HET5_AOE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HET5_AOE_C>();
	}
};
DUMPER7_ASSERTS_UGE_HET5_AOE_C;

}

