#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InteriorWindow_01_breakable

#include "Basic.hpp"

#include "BP_IGL_BRE_NAV_ATT_2HITS_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InteriorWindow_01_breakable.InteriorWindow_01_breakable_C
// 0x0000 (0x05F8 - 0x05F8)
class AInteriorWindow_01_breakable_C final : public ABP_IGL_BRE_NAV_ATT_2HITS_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("InteriorWindow_01_breakable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InteriorWindow_01_breakable_C")
	}
	static class AInteriorWindow_01_breakable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInteriorWindow_01_breakable_C>();
	}
};
DUMPER7_ASSERTS_AInteriorWindow_01_breakable_C;

}

