#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PD3TrafficLightBase

#include "Basic.hpp"

#include "PD3TrafficLightBase_classes.hpp"
#include "PD3TrafficLightBase_parameters.hpp"


namespace SDK
{

// Function PD3TrafficLightBase.PD3TrafficLightBase_C.ExecuteUbergraph_PD3TrafficLightBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APD3TrafficLightBase_C::ExecuteUbergraph_PD3TrafficLightBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PD3TrafficLightBase_C", "ExecuteUbergraph_PD3TrafficLightBase");

	Params::PD3TrafficLightBase_C_ExecuteUbergraph_PD3TrafficLightBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PD3TrafficLightBase.PD3TrafficLightBase_C.UpdatePool
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// ESBZTrafficLightStatus                  Status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<class UStaticMeshComponent*>&Pool                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const TArray<class USBZAmbientSoundComponent*>&PedestrianSoundEmitters                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void APD3TrafficLightBase_C::UpdatePool(ESBZTrafficLightStatus Status, const TArray<class UStaticMeshComponent*>& Pool, const TArray<class USBZAmbientSoundComponent*>& PedestrianSoundEmitters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PD3TrafficLightBase_C", "UpdatePool");

	Params::PD3TrafficLightBase_C_UpdatePool Parms{};

	Parms.Status = Status;
	Parms.Pool = std::move(Pool);
	Parms.PedestrianSoundEmitters = std::move(PedestrianSoundEmitters);

	UObject::ProcessEvent(Func, &Parms);
}

}

