#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PD3TrafficLightBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PD3TrafficLightBase.PD3TrafficLightBase_C
// 0x0010 (0x02F0 - 0x02E0)
class APD3TrafficLightBase_C final : public ASBZTrafficLights
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         BinFloat;                                          // 0x02E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PD3TrafficLightBase(int32 EntryPoint);
	void UpdatePool(ESBZTrafficLightStatus Status, const TArray<class UStaticMeshComponent*>& Pool, const TArray<class USBZAmbientSoundComponent*>& PedestrianSoundEmitters);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PD3TrafficLightBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PD3TrafficLightBase_C")
	}
	static class APD3TrafficLightBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APD3TrafficLightBase_C>();
	}
};
DUMPER7_ASSERTS_APD3TrafficLightBase_C;

}

