#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizedRoom_2

#include "Basic.hpp"

#include "RandomizedRoom_2_classes.hpp"
#include "RandomizedRoom_2_parameters.hpp"


namespace SDK
{

// Function RandomizedRoom_2.R_BranchBank_StorageRoom_C.RandomizedRoomTest_RemoteEvent1
// (BlueprintCallable, BlueprintEvent)

void AR_BranchBank_StorageRoom_C::RandomizedRoomTest_RemoteEvent1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_StorageRoom_C", "RandomizedRoomTest_RemoteEvent1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_2.R_BranchBank_StorageRoom_C.OnRandomSublevelPlaced
// (Event, Public, BlueprintEvent)

void AR_BranchBank_StorageRoom_C::OnRandomSublevelPlaced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_StorageRoom_C", "OnRandomSublevelPlaced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_2.R_BranchBank_StorageRoom_C.ExecuteUbergraph_R_BranchBank_StorageRoom
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_BranchBank_StorageRoom_C::ExecuteUbergraph_R_BranchBank_StorageRoom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_StorageRoom_C", "ExecuteUbergraph_R_BranchBank_StorageRoom");

	Params::R_BranchBank_StorageRoom_C_ExecuteUbergraph_R_BranchBank_StorageRoom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

