#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizedRoom_0

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomizedRoom_0.R_BranchBank_PowerRoom_C
// 0x0028 (0x0368 - 0x0340)
class AR_BranchBank_PowerRoom_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Var_OpenedDoor;                                    // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Var_CanistersRequired;                             // 0x0349(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_34A[0x2];                                      // 0x034A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Int_InteractedWithAllCanisters;                    // 0x034C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          VarCanistersEnabled;                               // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x7];                                      // 0x0351(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_GenericHackableComputer_C*          BP_GenericHackableComputer_2_ExecuteUbergraph_R_BranchBank_PowerRoom_RefProperty; // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZPlayerTriggerVolume*                SBZPlayerTriggerVolume_1_ExecuteUbergraph_R_BranchBank_PowerRoom_RefProperty; // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__R_BranchBank_PowerRoom_SBZPlayerTriggerVolume_1_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void HeistStateChanged(EPD3HeistState OldHeistState, EPD3HeistState CurrentHeistState);
	void BranchBank_Roof();
	void BranchBank_Stairs();
	void BranchBank_Kitchen();
	void OnRandomPlacementStarted();
	void BndEvt__R_BranchBank_PowerRoom_BP_GenericHackableComputer_2_K2Node_ActorBoundEvent_0_SBZHackableActorDelegate__DelegateSignature();
	void BndEvt__R_BranchBank_PowerRoom_BP_GenericHackableComputer_2_K2Node_ActorBoundEvent_4_SBZHackableActorDelegate__DelegateSignature();
	void RandomizedRoomTest_RemoteEvent1();
	void BranchBank_PowerRoomEnableComputer();
	void ExecuteUbergraph_R_BranchBank_PowerRoom(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("R_BranchBank_PowerRoom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"R_BranchBank_PowerRoom_C")
	}
	static class AR_BranchBank_PowerRoom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AR_BranchBank_PowerRoom_C>();
	}
};
DUMPER7_ASSERTS_AR_BranchBank_PowerRoom_C;

}

