#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizedRoom_1

#include "Basic.hpp"

#include "RandomizedRoom_1_classes.hpp"
#include "RandomizedRoom_1_parameters.hpp"


namespace SDK
{

// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.RandomizedRoomTest_RemoteEvent1
// (BlueprintCallable, BlueprintEvent)

void AR_BranchBank_SecurityRoom_C::RandomizedRoomTest_RemoteEvent1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "RandomizedRoomTest_RemoteEvent1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.OnRandomSublevelPlaced
// (Event, Public, BlueprintEvent)

void AR_BranchBank_SecurityRoom_C::OnRandomSublevelPlaced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "OnRandomSublevelPlaced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.BranchBank_Kitchen_Bkey
// (BlueprintCallable, BlueprintEvent)

void AR_BranchBank_SecurityRoom_C::BranchBank_Kitchen_Bkey()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "BranchBank_Kitchen_Bkey");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.BranchBank_Bottom_Bkey
// (BlueprintCallable, BlueprintEvent)

void AR_BranchBank_SecurityRoom_C::BranchBank_Bottom_Bkey()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "BranchBank_Bottom_Bkey");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.BranchBank_Stairs_Bkey
// (BlueprintCallable, BlueprintEvent)

void AR_BranchBank_SecurityRoom_C::BranchBank_Stairs_Bkey()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "BranchBank_Stairs_Bkey");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_1.R_BranchBank_SecurityRoom_C.ExecuteUbergraph_R_BranchBank_SecurityRoom
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_BranchBank_SecurityRoom_C::ExecuteUbergraph_R_BranchBank_SecurityRoom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_BranchBank_SecurityRoom_C", "ExecuteUbergraph_R_BranchBank_SecurityRoom");

	Params::R_BranchBank_SecurityRoom_C_ExecuteUbergraph_R_BranchBank_SecurityRoom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

