#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CuttingTool_Line

#include "Basic.hpp"

#include "WBP_CuttingTool_Line_classes.hpp"
#include "WBP_CuttingTool_Line_parameters.hpp"


namespace SDK
{

// Function WBP_CuttingTool_Line.WBP_CuttingTool_Line_C.ExecuteUbergraph_WBP_CuttingTool_Line
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CuttingTool_Line_C::ExecuteUbergraph_WBP_CuttingTool_Line(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CuttingTool_Line_C", "ExecuteUbergraph_WBP_CuttingTool_Line");

	Params::WBP_CuttingTool_Line_C_ExecuteUbergraph_WBP_CuttingTool_Line Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CuttingTool_Line.WBP_CuttingTool_Line_C.OnWidgetCutCompleted
// (Event, Public, BlueprintEvent)

void UWBP_CuttingTool_Line_C::OnWidgetCutCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CuttingTool_Line_C", "OnWidgetCutCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CuttingTool_Line.WBP_CuttingTool_Line_C.OnWidgetCut
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AtSegment                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CuttingTool_Line_C::OnWidgetCut(float AtSegment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CuttingTool_Line_C", "OnWidgetCut");

	Params::WBP_CuttingTool_Line_C_OnWidgetCut Parms{};

	Parms.AtSegment = AtSegment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CuttingTool_Line.WBP_CuttingTool_Line_C.OnWidgetInitialCut
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AtSegment                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CuttingTool_Line_C::OnWidgetInitialCut(float AtSegment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CuttingTool_Line_C", "OnWidgetInitialCut");

	Params::WBP_CuttingTool_Line_C_OnWidgetInitialCut Parms{};

	Parms.AtSegment = AtSegment;

	UObject::ProcessEvent(Func, &Parms);
}

}

